version: '3.9'

services:

  institution_app:
    container_name: institution_app
    image: millatevin/institution_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
       DATABASE_URL: jdbc:postgresql://school_repository:5432/postgres
       DATABASE_USERNAME: postgres
       DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - school_repository
  school_repository:
    container_name: school_repository
    image: postgres:14-alpine3.14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}